### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by CraigWally** [danrahn/MarkerEditorForPlex#18]
**Describe the bug**
program opens then immediately closes

**Copy from Log**
listen EACCES: permission denied 127.0.0.1:3232
Error: listen EACCES: permission denied 127.0.0.1:3232
    at Server.setupListenHandle [as _listen2] (node:net:1734:21)
    at listenInCluster (node:net:1799:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1948:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:110:8)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows,
 - Browser [Edge]
 - Version [e.g. 2.6.3]

**Additional context**
Had previously worked flawlessly

**Comment by danrahn** [comment]
Seems like something else is using that port (or at least is preventing other applications from using it). If you don't have any other programs running that might also be using that port, you could try running `net stop winnat` followed by `net start winnat` from an admin command prompt, as suggested by [this thread](https://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports/65698209#65698209). You could also try [changing the `port` in config.json](https://github.com/danrahn/MarkerEditorForPlex/wiki/configuration#port) to see if the application is able to start on a different port.

**Comment by CraigWally** [comment]
Changing port - that fixed it
Thanks
