### ISSUE TITLE
Dark Mode Settings checkboxes are confusingly colored

### ISSUE THREAD

**Issue by lightmaster** [danrahn/MarkerEditorForPlex#23]
When using Dark Mode, the Settings Checkboxes are a bit confusing. For instance, in the screenshot below, first instinct is to say that "Collapse Thumbnails" is the only check box that is checked, when in it's really the only checkbox that's not checked. In Light Mode, a white box is unchecked, and a colored box is checked, however in Dark Mode, a colored box is uncheck, and a white box is checked. Perhaps either flipping the colors (so white is unchecked) or adding an X or something would make it less confusing.

![image](https://github.com/danrahn/MarkerEditorForPlex/assets/5307827/5f3c8971-b015-4418-acea-1a3a9fb7efe2)

**Comment by danrahn** [comment]
I'll look into adjusting this. I was going for, "a color that matches the background is unchecked, and a color that contrasts with the background is on", which is a fairly standard pattern, but the lack of an actual check the the settings checkboxes is definitely confusing.
