### ISSUE TITLE
[Feature Request] add username-password feature

### ISSUE THREAD

**Issue by erickyun** [danrahn/MarkerEditorForPlex#27]
Hi,

I would appreciate if there was any login/password feature.

**Comment by danrahn** [comment]
Implemented in af125ecce14546b446ef1d87e28c451444796976, and should be available in the latest beta: [v2.8.0-beta](https://github.com/danrahn/MarkerEditorForPlex/releases/tag/v2.8.0-beta). It's been minimally tested, so definitely let me know if it's not working as expected.

**Comment by erickyun** [comment]
> Implemented in [af125ec](https://github.com/danrahn/MarkerEditorForPlex/commit/af125ecce14546b446ef1d87e28c451444796976), and should be available in the latest beta: [v2.8.0-beta](https://github.com/danrahn/MarkerEditorForPlex/releases/tag/v2.8.0-beta). It's been minimally tested, so definitely let me know if it's not working as expected.

Thank you! I will test it and let you know.
