### ISSUE TITLE
Why force the app to listen on 0.0.0.0 in docker mode?

### ISSUE THREAD

**Issue by pannal** [danrahn/MarkerEditorForPlex#30]
Pretty much what the title says. I'd like it to only listen on a specific ip/host (e.g. 127.0.0.1); why does the app bind to 0.0.0.0 when it's launched in docker?

**Comment by danrahn** [comment]
Mostly laziness, since I don't use Docker and no one had complained about it yet. I'll look into making it configurable.

**Comment by danrahn** [comment]
The restriction should be gone in [2.8.0-beta.2](https://github.com/danrahn/MarkerEditorForPlex/releases/tag/v2.8.0-beta.2). It's mostly untested though, so let me know if it's not working as expected.
