### ISSUE TITLE
Support baseURL

### ISSUE THREAD

**Issue by pannal** [danrahn/MarkerEditorForPlex#31]
When running behind a reverse proxy, such as NGINX, the app expects to run at the server root path.

A baseURL setting would be great, so that it can run under a subfolder (e.g. domain.com/markereditor).

Thanks!

**Comment by danrahn** [comment]
Thanks for the suggestion! I'll see what I can do here.

**Comment by danrahn** [comment]
There's a new `baseUrl` setting in [2.8.0-beta.2](https://github.com/danrahn/MarkerEditorForPlex/releases/tag/v2.8.0-beta.2). Like your other request, this hasn't been tested extensively, so let me know if it's not working as expected.
