### ISSUE TITLE
Credits Marker late

### ISSUE THREAD

**Issue by Iceman253** [danrahn/MarkerEditorForPlex#32]
**Describe the bug**
The Credit marker shows up several seconds after I set it to show up and then it skips to several seconds earlier than I set it.

**Expected behavior**
Credits appearing at the time I set it to and then going to the end of the show.

**Desktop:**
 - OS: Windows 23H2
 - Browser: Microsoft Edge

**Additional Information:**
The thumbnails it shows me are the correct times but the skip button is what is not working.

**Comment by danrahn** [comment]
Plex made a change that offsets credits by 2 seconds. The database will have the expected timestamp, but if you use Get Info on the media, the `<Marker>`s will start 2 seconds later, and end 2 seconds earlier (if it's not a `final` marker):

![image](https://github.com/user-attachments/assets/d6ffe788-921e-4e70-9feb-c3b657922117)

I'm hesitant to bake that offset into this application in case they decide to tweak it later, though it might be worth making it a configurable option.
